apiVersion: apps/v1
kind: Deployment
meta
  name: sample-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-microservice
  template:
    meta
      labels:
        app: sample-microservice
    spec:
      containers:
      - name: sample-microservice
        image: quay.io/myorg/sample-microservice:latest
        ports:
        - containerPort: 8080
